// SNKRS HUB — product catalogue
// Images are placeholders generated by placeholderImage() in js/placeholder.js.
// Swap each images[] entry for a real photo URL or file path before launch.
// Each colorway holds its own image so the gallery can switch on click.

const PRODUCTS = [
  {
    id: "aero-runner",
    name: "Aero Runner",
    category: "men",
    badge: "New",
    price: 42,
    description:
      "A lightweight daily trainer with a responsive foam sole and a breathable knit upper. Cleaned, inspected and ready to ship same week.",
    sizes: [40, 41, 42, 43, 44, 45],
    colors: [
      {
        name: "Cloud White",
        hex: "#f2efe9",
        images: [
          placeholderImage("Aero Runner — Cloud White"),
          placeholderImage("Aero Runner — Cloud White, alt angle")
        ]
      },
      {
        name: "Blackout",
        hex: "#141414",
        images: [
          placeholderImage("Aero Runner — Blackout"),
          placeholderImage("Aero Runner — Blackout, alt angle")
        ]
      }
    ]
  },
  {
    id: "court-classic",
    name: "Court Classic",
    category: "men",
    badge: "Restock",
    price: 38,
    description:
      "The everyday court silhouette. Full-grain leather panels, rubber cupsole, broken in just enough to feel right on day one.",
    sizes: [40, 41, 42, 43, 44],
    colors: [
      {
        name: "Bone",
        hex: "#e7e0d2",
        images: [
          placeholderImage("Court Classic — Bone"),
          placeholderImage("Court Classic — Bone, alt angle")
        ]
      },
      {
        name: "Crimson",
        hex: "#b3271e",
        images: [
          placeholderImage("Court Classic — Crimson"),
          placeholderImage("Court Classic — Crimson, alt angle")
        ]
      }
    ]
  },
  {
    id: "street-mid",
    name: "Street Mid",
    category: "men",
    badge: "",
    price: 45,
    description:
      "Mid-top silhouette built for the block, not the treadmill. Padded collar, canvas body, a sole that grips wet pavement.",
    sizes: [41, 42, 43, 44, 45, 46],
    colors: [
      {
        name: "Olive",
        hex: "#4b5320",
        images: [
          placeholderImage("Street Mid — Olive"),
          placeholderImage("Street Mid — Olive, alt angle")
        ]
      },
      {
        name: "Jet Black",
        hex: "#0e0e0e",
        images: [
          placeholderImage("Street Mid — Jet Black"),
          placeholderImage("Street Mid — Jet Black, alt angle")
        ]
      }
    ]
  },
  {
    id: "featherweight",
    name: "Featherweight",
    category: "women",
    badge: "New",
    price: 40,
    description:
      "Built for people who walk the city all day. Sock-fit ankle, molded midsole, barely-there weight on the foot.",
    sizes: [36, 37, 38, 39, 40],
    colors: [
      {
        name: "Blush",
        hex: "#d8a7a1",
        images: [
          placeholderImage("Featherweight — Blush"),
          placeholderImage("Featherweight — Blush, alt angle")
        ]
      },
      {
        name: "Chalk",
        hex: "#eae6dd",
        images: [
          placeholderImage("Featherweight — Chalk"),
          placeholderImage("Featherweight — Chalk, alt angle")
        ]
      }
    ]
  },
  {
    id: "trail-edge",
    name: "Trail Edge",
    category: "women",
    badge: "Sale",
    price: 35,
    originalPrice: 46,
    description:
      "An off-road sole with real lug depth, wrapped in a runner's upper. Made for the gravel paths past the last bus stop.",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: [
      {
        name: "Forest",
        hex: "#1f7a4d",
        images: [
          placeholderImage("Trail Edge — Forest"),
          placeholderImage("Trail Edge — Forest, alt angle")
        ]
      },
      {
        name: "Slate",
        hex: "#4a4f55",
        images: [
          placeholderImage("Trail Edge — Slate"),
          placeholderImage("Trail Edge — Slate, alt angle")
        ]
      }
    ]
  },
  {
    id: "junior-dash",
    name: "Junior Dash",
    category: "kids",
    badge: "",
    price: 22,
    description:
      "Velcro strap, reinforced toe, a sole that survives the playground. Sized for growing feet, priced for growing families.",
    sizes: [30, 31, 32, 33, 34, 35],
    colors: [
      {
        name: "Sky",
        hex: "#5b8cb8",
        images: [
          placeholderImage("Junior Dash — Sky"),
          placeholderImage("Junior Dash — Sky, alt angle")
        ]
      },
      {
        name: "Sunburst",
        hex: "#f2c14e",
        images: [
          placeholderImage("Junior Dash — Sunburst"),
          placeholderImage("Junior Dash — Sunburst, alt angle")
        ]
      }
    ]
  },
  {
    id: "flex-knit",
    name: "Flex Knit",
    category: "women",
    badge: "New",
    price: 44,
    description:
      "A stretch-knit upper that moves with the foot, on a foam stack tuned for standing shifts and long errands alike.",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: [
      {
        name: "Rose",
        hex: "#c9707a",
        images: [
          placeholderImage("Flex Knit — Rose"),
          placeholderImage("Flex Knit — Rose, alt angle")
        ]
      },
      {
        name: "Ink",
        hex: "#1c1f26",
        images: [
          placeholderImage("Flex Knit — Ink"),
          placeholderImage("Flex Knit — Ink, alt angle")
        ]
      }
    ]
  },
  {
    id: "heritage-eighty",
    name: "Heritage Eighty",
    category: "men",
    badge: "Sale",
    price: 33,
    originalPrice: 41,
    description:
      "A retro court shape brought back from the archive. Vulcanised sole, waxed laces, a shoe that looks better lived-in.",
    sizes: [40, 41, 42, 43, 44, 45, 46],
    colors: [
      {
        name: "Cream",
        hex: "#efe7d8",
        images: [
          placeholderImage("Heritage Eighty — Cream"),
          placeholderImage("Heritage Eighty — Cream, alt angle")
        ]
      },
      {
        name: "Navy",
        hex: "#232f45",
        images: [
          placeholderImage("Heritage Eighty — Navy"),
          placeholderImage("Heritage Eighty — Navy, alt angle")
        ]
      }
    ]
  }
];

function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id);
}
