// SNKRS HUB — product catalogue (women's sneakers, organized by brand)
// Images are placeholders generated by placeholderImage() in js/placeholder.js.
// Swap each images[] entry for a real photo URL or file path before launch.
// Each colorway holds its own image so the gallery can switch on click.

const PRODUCTS = [
  {
    id: "aero-runner",
    name: "Aero Runner",
    brand: "Nike",
    badge: "New",
    price: 42,
    description:
      "A lightweight daily trainer with a responsive foam sole and a breathable knit upper. Cleaned, inspected and ready to ship same week.",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: [
      {
        name: "Cloud White",
        hex: "#f2efe9",
        images: [
          placeholderImage("Nike Aero Runner — Cloud White"),
          placeholderImage("Nike Aero Runner — Cloud White, alt angle")
        ]
      },
      {
        name: "Blackout",
        hex: "#141414",
        images: [
          placeholderImage("Nike Aero Runner — Blackout"),
          placeholderImage("Nike Aero Runner — Blackout, alt angle")
        ]
      }
    ]
  },
  {
    id: "court-classic",
    name: "Court Classic",
    brand: "Adidas",
    badge: "Restock",
    price: 38,
    description:
      "The everyday court silhouette. Full-grain leather panels, rubber cupsole, broken in just enough to feel right on day one.",
    sizes: [36, 37, 38, 39, 40],
    colors: [
      {
        name: "Bone",
        hex: "#e7e0d2",
        images: [
          placeholderImage("Adidas Court Classic — Bone"),
          placeholderImage("Adidas Court Classic — Bone, alt angle")
        ]
      },
      {
        name: "Crimson",
        hex: "#b3271e",
        images: [
          placeholderImage("Adidas Court Classic — Crimson"),
          placeholderImage("Adidas Court Classic — Crimson, alt angle")
        ]
      }
    ]
  },
  {
    id: "street-mid",
    name: "Street Mid",
    brand: "Puma",
    badge: "",
    price: 45,
    description:
      "Mid-top silhouette built for the block, not the treadmill. Padded collar, canvas body, a sole that grips wet pavement.",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: [
      {
        name: "Olive",
        hex: "#4b5320",
        images: [
          placeholderImage("Puma Street Mid — Olive"),
          placeholderImage("Puma Street Mid — Olive, alt angle")
        ]
      },
      {
        name: "Jet Black",
        hex: "#0e0e0e",
        images: [
          placeholderImage("Puma Street Mid — Jet Black"),
          placeholderImage("Puma Street Mid — Jet Black, alt angle")
        ]
      }
    ]
  },
  {
    id: "featherweight",
    name: "Featherweight",
    brand: "New Balance",
    badge: "New",
    price: 40,
    description:
      "Built for people who walk the city all day. Sock-fit ankle, molded midsole, barely-there weight on the foot.",
    sizes: [36, 37, 38, 39, 40],
    colors: [
      {
        name: "Blush",
        hex: "#d8a7a1",
        images: [
          placeholderImage("New Balance Featherweight — Blush"),
          placeholderImage("New Balance Featherweight — Blush, alt angle")
        ]
      },
      {
        name: "Chalk",
        hex: "#eae6dd",
        images: [
          placeholderImage("New Balance Featherweight — Chalk"),
          placeholderImage("New Balance Featherweight — Chalk, alt angle")
        ]
      }
    ]
  },
  {
    id: "trail-edge",
    name: "Trail Edge",
    brand: "Vans",
    badge: "Sale",
    price: 35,
    originalPrice: 46,
    description:
      "An off-road sole with real lug depth, wrapped in a runner's upper. Made for the gravel paths past the last bus stop.",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: [
      {
        name: "Forest",
        hex: "#1f7a4d",
        images: [
          placeholderImage("Vans Trail Edge — Forest"),
          placeholderImage("Vans Trail Edge — Forest, alt angle")
        ]
      },
      {
        name: "Slate",
        hex: "#4a4f55",
        images: [
          placeholderImage("Vans Trail Edge — Slate"),
          placeholderImage("Vans Trail Edge — Slate, alt angle")
        ]
      }
    ]
  },
  {
    id: "city-dash",
    name: "City Dash",
    brand: "Converse",
    badge: "",
    price: 30,
    description:
      "A low-profile canvas classic, reinforced toe and a sole that survives every kind of pavement Amman can throw at it.",
    sizes: [36, 37, 38, 39, 40],
    colors: [
      {
        name: "Sky",
        hex: "#5b8cb8",
        images: [
          placeholderImage("Converse City Dash — Sky"),
          placeholderImage("Converse City Dash — Sky, alt angle")
        ]
      },
      {
        name: "Sunburst",
        hex: "#f2c14e",
        images: [
          placeholderImage("Converse City Dash — Sunburst"),
          placeholderImage("Converse City Dash — Sunburst, alt angle")
        ]
      }
    ]
  },
  {
    id: "flex-knit",
    name: "Flex Knit",
    brand: "Reebok",
    badge: "New",
    price: 44,
    description:
      "A stretch-knit upper that moves with the foot, on a foam stack tuned for standing shifts and long errands alike.",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: [
      {
        name: "Rose",
        hex: "#c9707a",
        images: [
          placeholderImage("Reebok Flex Knit — Rose"),
          placeholderImage("Reebok Flex Knit — Rose, alt angle")
        ]
      },
      {
        name: "Ink",
        hex: "#1c1f26",
        images: [
          placeholderImage("Reebok Flex Knit — Ink"),
          placeholderImage("Reebok Flex Knit — Ink, alt angle")
        ]
      }
    ]
  },
  {
    id: "heritage-eighty",
    name: "Heritage Eighty",
    brand: "ASICS",
    badge: "Sale",
    price: 33,
    originalPrice: 41,
    description:
      "A retro court shape brought back from the archive. Vulcanised sole, waxed laces, a shoe that looks better lived-in.",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: [
      {
        name: "Cream",
        hex: "#efe7d8",
        images: [
          placeholderImage("ASICS Heritage Eighty — Cream"),
          placeholderImage("ASICS Heritage Eighty — Cream, alt angle")
        ]
      },
      {
        name: "Navy",
        hex: "#232f45",
        images: [
          placeholderImage("ASICS Heritage Eighty — Navy"),
          placeholderImage("ASICS Heritage Eighty — Navy, alt angle")
        ]
      }
    ]
  }
];

const BRANDS = ["Nike", "Adidas", "New Balance", "Puma", "Vans", "Converse", "Reebok", "ASICS"];

function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id);
}
